<?php
// module/Forumdash/view/forumdash/forumdash/addforum.phtml:

$title = 'Add new forum';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('forumdash', array('action' => 'addforum')));

// die(var_dump($form));

$form->prepare();

// die("I'm never called!");
echo "<br><br>";

if (!empty($err))
{
    echo "<h2>" . $this->escapeHtml($err) . "</h2>";
    echo "<br><br>";
}


echo $this->form()->openTag($form);
echo $this->formCollection($form);
/* echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit')); */
echo $this->form()->closeTag(); 