<?php
// module/Forumdash/view/forumdash/forumdash/addforum.phtml:

$title = 'Add more topics. Project: ' . $projectname;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('forumdash', array('action' => 'addtopics')));
$form->setAttribute('action', $this->url(
		'forumdash',
		array(
			'action' => 'addtopics',
			'id'     => $this->id,
		)
	));
// die(var_dump($form));

$form->prepare();

// die("I'm never called!");

echo $this->form()->openTag($form);
echo $this->formCollection($form);
/* echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit')); */
echo $this->form()->closeTag(); 