<?php
// module/Album/view/album/album/index.phtml:

$title = 'Forum Poster - Dashboard';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th style="width: 53px;">Id</th>
    <th style="width: 150px;">ForumName</th>
    <th style="width: 250px;">ForumStatus</th>
    <th>Success<br>Rate</th>
    <th>NextTopic<br>Aff.program</th>
    <th style="width: 300px;">Actions</th>
</tr>
<?php foreach ($projects as $project) : ?>
<tr>
    <td><?php echo $this->escapeHtml($project->getId());?></td>
    <td><?php echo $this->escapeHtml($project->getProjectName());?></td>
    <td><?php echo $this->escapeHtml($project->getProjectStatus());?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
        <a href="<?php echo $this->url('forumdash', 
                array('action'=>'edit', 'id' => $project->getId()));
                ?>">Add keywords</a>&nbsp;|&nbsp;
        <a href="<?php echo $this->url('forumdash', 
                array('action'=>'showlatest', 'id' => $project->getId()));
                ?>">Show posts</a>&nbsp;|&nbsp;
        <a href="<?php echo $this->url('forumdash', 
                array('action'=>'addtopics', 'id' => $project->getId()));
                ?>">Add topics</a>&nbsp;
    </td>
<?php
/*  
	<td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>"> Show posts</a>&nbsp;|&nbsp;
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>"> Edit Settings</a>
    </td>
*/
?>
</tr>
<?php endforeach; ?>
</table> 
<p><a class="btn btn-large btn-primary" href="<?php echo $this->url('forumdash', array('action'=>'addforum')); ?>">Add forum</a></p>
<p><a class="btn" href="<?php echo $this->url('forumdash', array('action'=>'addaccountproperty')); ?>">Add a new account property</a></p>
<p><a class="btn" href="<?php echo $this->url('forumdash', array('action'=>'showproxies')); ?>">Show Active Proxies</a></p>

