<?php
$no_visible_elements=true;
//include('header.php'); ?>

			<div class="row-fluid">
				<div class="span12 center login-header">
					<h2>Welcome to Charisma</h2>
				</div><!--/span-->
			</div><!--/row-->
			
			<div class="row-fluid">
				<div class="well span5 center login-box">
					<div class="alert alert-info">
						Please login with your Username and Password.
					</div>
											            <?php echo $this->content; ?>				

				</div><!--/span-->
			</div><!--/row-->
<?php //include('footer.php'); ?>
